=== VillyCoder26/Impresiones3DAVG/Ficheros_xml/Impresiones3DAVG.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified">

    <!--DOCUMENTACION DEL ESQUEMA -->
    <xs:annotation>
        <xs:documentation xml:lang="es-es">
            <titulo>Impresiones 3DAVG</titulo>
            <modulo>LMGSI</modulo>
            <fecha_creacion>16/05/2024</fecha_creacion>
            <autor>Antonio Vilarta Gil</autor>
        </xs:documentation>
    </xs:annotation>

  <!-- Definición de tipos de datos -->
  <xs:simpleType name="tipoImpresion">
    <xs:restriction base="xs:string">
      <xs:enumeration value="FDM"/>
      <xs:enumeration value="SLA"/>
    </xs:restriction>
  </xs:simpleType>

  

  <!-- Definición del elemento raíz -->
  
  <xs:element name="Impresiones3DAVG">
    <xs:complexType>
      <xs:sequence>
        <!-- Sección de Portada -->
        <xs:element name="Portada">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Descripcion" type="xs:string"/>
              <xs:element name="Usos">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Uso" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <!-- Sección de Impresoras3D -->
        <xs:element name="Impresoras3D">
          <xs:complexType>
            <xs:sequence>
              <!-- Sección de Marcas -->
              <xs:element name="Marcas" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Marca" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <!-- Sección de Impresoras -->
                          <xs:element name="Impresora" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="Modelo" type="xs:string"/>
                                <xs:element name="Tipo" type="tipoImpresion"/>
                                <xs:element name="Descripcion" type="xs:string"/>
                                <xs:element name="Precio">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                      <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="codigo">
                                <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                    <xs:pattern value="IMPR-[\w]+"/>
                                  </xs:restriction>
                                </xs:simpleType>
                              </xs:attribute>
                              <xs:attribute name="nombre" type="xs:string" use="required"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="nombre" type="xs:string" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            <!-- Sección de Filamentos -->
            <xs:element name="Filamentos">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="Tipos" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="Tipo" maxOccurs="unbounded">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Descripcion" type="xs:string"/>
                              <xs:element name="Precio">
                                <xs:simpleType>
                                  <xs:restriction base="xs:decimal">
                                    <xs:fractionDigits value="2"/>
                                  </xs:restriction>
                                </xs:simpleType>
                              </xs:element>
                              <xs:element name="Usos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Uso" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                                     </xs:sequence>
                                </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                            <xs:attribute name="codigo">
                              <xs:simpleType>
                                <xs:restriction base="xs:string">
                                  <xs:pattern value="FIL-[\w]+"/>
                                </xs:restriction>
                              </xs:simpleType>
                            </xs:attribute>
                            <xs:attribute name="nombre" type="xs:string" use="required"/>
                          </xs:complexType>
                        </xs:element>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <!-- Sección de Programas -->
            <xs:element name="Programas">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="Programa" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="Descripcion" type="xs:string"/>
                      </xs:sequence>
                      <xs:attribute name="codigo">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:pattern value="PROG-[\w]+"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                      <xs:attribute name="nombre" type="xs:string" use="required"/>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <!-- Sección de Impresiones -->
            <xs:element name="Impresiones">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="Impresion" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="Nombre" type="xs:string"/>
                        <xs:element name="TipoArchivo" type="xs:string"/>
                        <xs:element name="Impresora" type="xs:string"/>
                        <xs:element name="Filamento" type="xs:string"/>
                        <xs:element name="Programas">
                          <xs:complexType>
                            <xs:sequence>
                              <xs:element name="Programa" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                            </xs:sequence>
                          </xs:complexType>
                        </xs:element>
                        <xs:element name="Soportes" type="xs:string"/>
                        <xs:element name="Descripcion" type="xs:string"/>
                        <xs:element name="Precio">
                          <xs:simpleType>
                            <xs:restriction base="xs:decimal">
                              <xs:fractionDigits value="2"/>
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:element>
                      </xs:sequence>
                      <xs:attribute name="codigo">
                        <xs:simpleType>
                          <xs:restriction base="xs:string">
                            <xs:pattern value="IMPRE-[\w]+"/>
                          </xs:restriction>
                        </xs:simpleType>
                      </xs:attribute>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== VillyCoder26/Impresiones3DAVG/Ficheros_xml/Impresiones3DAVG_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<Impresiones3DAVG xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
        xs:noNamespaceSchemaLocation="Impresiones3DAVG.xsd">
    <Portada>
        <Descripcion>Las impresoras 3D han revolucionado la fabricación permitiendo la creación de objetos físicos a partir de modelos digitales. Se utilizan en diversas industrias como la automotriz, médica y de entretenimiento.</Descripcion>
        <Usos>
            <Uso>Prototipado rápido</Uso>
            <Uso>Producción de herramientas</Uso>
            <Uso>Fabricación de piezas personalizadas</Uso>
            <Uso>Educación</Uso>
            <Uso>Hobby y arte</Uso>
        </Usos>
    </Portada>
    <Impresoras3D>
        <Marcas>
            <Marca nombre="Artillery">
                <Impresora codigo="IMPR-ARTIH" nombre="Artillery Hornet">
                    <Modelo>Hornet</Modelo>
                    <Tipo>FDM</Tipo>
                    <Descripcion>La nueva impresora 3D Artillery Hornet, es una impresora 3D de estilo cartesiano todo en uno. 
                        La impresora Artillery Hornet es ultra silenciosa y tiene controladores 32bits paso a paso, tiene un extrusor tipo bowden, nozzle 0.4mm compatible E3D V6, eje Z doble, cama calefactada de corriente CA y pantalla táctil TFT.</Descripcion>
                    <Precio>200.05</Precio>
                </Impresora>
                <Impresora codigo="IMPR-ARTIX1" nombre="Artillery Sidewinder X1">
                    <Modelo>Sidewinder X1</Modelo>
                    <Tipo>FDM</Tipo>
                    <Descripcion>Artillery Sidewinder X1 es una impresora 3D con mayúsculas, ofrece una calidad de impresión difícil de superar.
                        Su sistema de extrusión directa y su gran versatilidad le permiten imprimir muy bien con una amplia gama de materiales, incluido flexibles, donde supera a la mayoría.
                        Destaca por su sigilosa impresión y rapidez, tanto en velocidad de impresión, que es realmente alta, como en la velocidad de calentamiento de la cama.
                        Esta impresora 3D Artillery tiene de detector de falta de filamento, pausa y reanudación de impresión tras un corte de corriente.</Descripcion>
                    <Precio>435</Precio>
                </Impresora>
            </Marca>
            <Marca nombre="AnyCubic">
                <Impresora codigo="IMPR-ANYPHX2" nombre="Anycubic Photon Mono X2">
                    <Modelo>Mono X2</Modelo>
                    <Tipo>SLA</Tipo>
                    <Descripcion>La Anycubic Photon Mono X2 es una impresora 3D de resina LCD que destaca por su pantalla monocromática 4K de 6.6 pulgadas, la cual permite imprimir modelos con una increíble precisión y detalles finos. 
                        Esta impresora está diseñada tanto para profesionales como para aficionados avanzados que buscan resultados de alta calidad en sus proyectos de impresión 3D.</Descripcion>
                    <Precio>600.99</Precio>
                </Impresora>
                <Impresora codigo="IMPR-ANYI3MS" nombre="Anycubic i3 Mega S">
                    <Modelo>i3 Mega S</Modelo>
                    <Tipo>FDM</Tipo>
                    <Descripcion>La Anycubic i3 Mega S es una impresora 3D FDM robusta y fácil de usar, ideal para principiantes y usuarios avanzados. 
                        Con una estructura metálica sólida y varias características que facilitan la experiencia de impresión, la i3 Mega S es conocida por su fiabilidad y calidad de impresión.</Descripcion>
                    <Precio>812</Precio>
                </Impresora>
            </Marca>
            <Marca nombre="Creality">
                <Impresora codigo="IMPR-CREALITY01" nombre="Creality LD-002H">
                    <Modelo>LD-002H</Modelo>
                    <Tipo>SLA</Tipo>
                    <Descripcion>Impresora 3D de resina con pantalla monocromática 2K, ideal para impresiones detalladas y rápidas.</Descripcion>
                    <Precio>215.50</Precio>
                </Impresora>
                <Impresora codigo="IMPR-CREALITY02" nombre="Creality Ender 3 V2">
                    <Modelo>Ender 3 V2</Modelo>
                    <Tipo>FDM</Tipo>
                    <Descripcion>Impresora 3D FDM popular y asequible, ideal para principiantes y makers.</Descripcion>
                    <Precio>220</Precio>
                </Impresora>
            </Marca>
            <Marca nombre="Prusa Research">
                <Impresora codigo="IMPR-PRUSA01" nombre="Prusa Research SL1">
                    <Modelo>SL1</Modelo>
                    <Tipo>SLA</Tipo>
                    <Descripcion>Impresora 3D de resina de alta calidad con pantalla LCD de alta resolución.</Descripcion>
                    <Precio>523.67</Precio>
                </Impresora>
                <Impresora codigo="IMPR-PRUSA02" nombre="Prusa Research Prusa i3 MK3S+">
                    <Modelo>i3 MK3S+</Modelo>
                    <Tipo>FDM</Tipo>
                    <Descripcion>Impresora 3D FDM de calidad reconocida por su fiabilidad y facilidad de uso.</Descripcion>
                    <Precio>750.20</Precio>
                </Impresora>
            </Marca> 
        </Marcas>
    <Filamentos>
        <Tipos>
            <Tipo codigo="FIL-PL01" nombre="PLA">
                <Descripcion>Filamento biodegradable y fácil de imprimir.</Descripcion>
                <Precio>25</Precio>
                <Usos>
                    <Uso>Prototipado rápido</Uso>
                    <Uso>Objetos decorativos</Uso>
                </Usos>
            </Tipo>
            <Tipo codigo="FIL-ABS01" nombre="ABS">
                <Descripcion>Filamento resistente y duradero, ideal para piezas funcionales.</Descripcion>
                <Precio>30</Precio>
                <Usos>
                    <Uso>Piezas mecánicas</Uso>
                    <Uso>Juguetes</Uso>
                </Usos>
            </Tipo>
            <Tipo codigo="FIL-PETG01" nombre="PETG">
                <Descripcion>Filamento resistente y flexible, ideal para aplicaciones mecánicas y funcionales.</Descripcion>
                <Precio>35</Precio>
                <Usos>
                    <Uso>Piezas funcionales</Uso>
                    <Uso>Prototipado</Uso>
                </Usos>
            </Tipo>
            <Tipo codigo="FIL-PU01" nombre="TPU">
                <Descripcion>Filamento flexible con alta resistencia al impacto, perfecto para impresiones que requieren flexibilidad.</Descripcion>
                <Precio>40</Precio>
                <Usos>
                    <Uso>Calzado</Uso>
                    <Uso>Juguetes</Uso>
                </Usos>
            </Tipo>
            <Tipo codigo="FIL-Nylon01" nombre="Nylon">
                <Descripcion>Filamento resistente a la abrasión y al impacto, adecuado para piezas duraderas y funcionales.</Descripcion>
                <Precio>50</Precio>
                <Usos>
                    <Uso>Engranajes</Uso>
                    <Uso>Componentes de maquinaria</Uso>
                </Usos>
            </Tipo>
            <Tipo codigo="FIL-Resina01" nombre="Resina Estándar">
                <Descripcion>Resina estándar para impresión SLA, adecuada para una variedad de aplicaciones.</Descripcion>
                <Precio>60</Precio>
                <Usos>
                    <Uso>Prototipado</Uso>
                    <Uso>Modelado dental</Uso>
                </Usos>
            </Tipo>
            <Tipo codigo="FIL-Resina02" nombre="Resina para Joyería">
                <Descripcion>Resina especializada para impresión de joyería con alta precisión y detalles finos.</Descripcion>
                <Precio>70</Precio>
                <Usos>
                    <Uso>Impresión de joyería</Uso>
                </Usos>
            </Tipo>
            <Tipo codigo="FIL-Resina03" nombre="Resina Dental">
                <Descripcion>Resina médica para impresiones dentales de alta precisión y biocompatibilidad.</Descripcion>
                <Precio>80</Precio>
                <Usos>
                    <Uso>Odontología</Uso>
                    <Uso>Ortodoncia</Uso>
                </Usos>
            </Tipo>
        </Tipos>
    </Filamentos>
    <Programas>
        <Programa nombre="Cura">
            <Descripcion>Software de corte 3D gratuito y de código abierto.</Descripcion>
        </Programa>
        <Programa nombre="PrusaSlicer">
            <Descripcion>Programa de corte 3D avanzado para impresoras Prusa.</Descripcion>
        </Programa>
        <Programa nombre="Simplify3D">
            <Descripcion>Software de corte 3D profesional con características avanzadas.</Descripcion>
        </Programa>
    </Programas>
    <Impresiones>
        <Impresion codigo="IMPRE-IMP01">
            <Nombre>Prototipo de Automóvil</Nombre>
            <TipoArchivo>STL</TipoArchivo>
            <Impresora>Artillery Hornet</Impresora>
            <Filamento>PLA</Filamento>
            <Programas>
                <Programa>Cura</Programa>
            </Programas>
            <Soportes>Impresión con soportes automáticos generados por Cura.</Soportes>
            <Descripcion>Un prototipo a escala de un automóvil usando impresora Artillery Hornet y filamento PLA.</Descripcion>
            <Precio>25</Precio>
        </Impresion>
        <Impresion codigo="IMPRE-IMP02">
            <Nombre>Juguete Mecánico</Nombre>
            <TipoArchivo>OBJ</TipoArchivo>
            <Impresora>Artillery Sidewinder X1</Impresora>
            <Filamento>ABS</Filamento>
            <Programas>
                <Programa>PrusaSlicer</Programa>
            </Programas>
            <Soportes>Soportes manuales diseñados en PrusaSlicer.</Soportes>
            <Descripcion>Un juguete mecánico impreso con la impresora Artillery Sidewinder X1 y filamento ABS.</Descripcion>
            <Precio>10</Precio>
        </Impresion>
        <Impresion codigo="IMPRE-IMP03">
